### ISSUE TITLE
Restarting a watcher container requires re-validating the license.

### ISSUE THREAD

**Issue by BrianAllred** [filebot/filebot-docker#23]
This is especially cumbersome because I use watchtower to keep containers up to date. If watchtower restarts the container automatically due to an update, then my files will stop processing.

**Comment by BrianAllred** [comment]
Actually, looks like the /data directory wasn't consistent between when watcher was running (`/data/filebot`) and when I input the license (`/data`). Confusing, but fixable.

**Comment by rednoah** [comment]
Presumably, you're sometimes running the `filebot` process as `user 1000 named filebot`, and sometimes as `user 0 named root`. Each user has its own `$HOME` folder because you would run into permission issues if different users create / read / write files in the same folder. Files created by `root` are particularly problematic for normal users.

[[SIGNED](https://github.com/filebot/filebot-docker?tab=readme-ov-file#how-do-i-activate-my-license)](https://github.com/filebot/filebot-docker/blob/master/README.md#how-do-i-activate-my-license) explains the issue.
